### ISSUE TITLE
npm install dynamo-archive fails

### ISSUE THREAD

**Issue by jimmys** [yegor256/dynamo-archive#15]
I have a brand new installation of node and npm on OS X 10.10.4

> $ uname -a
Darwin macbook 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
> $ node -v
> v0.12.7
> $ npm -v
> 2.12.1

When I run ``npm install dynamo-archive`` I get the following messages. I cannot figure out why it does not work, and I am a node novice so I am not sure where to go next.

>	$ npm install dynamo-archive
>	-
>	> sleep@1.1.8 install /Users/my_user/node_modules/dynamo-archive/node_modules/sleep
>	> node build.js || nodejs build.js
>
>	child_process: customFds option is deprecated, use stdio instead.
>	gyp: dynamo-archive not found (cwd: /Users/my_user/node_modules/dynamo-archive/node_modules/sleep) while trying to load dynamo-archive
>	gyp ERR! configure error
>	gyp ERR! stack Error: `gyp` failed with exit code: 1
>	gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
>	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
>	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
>	gyp ERR! System Darwin 14.4.0
>	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "dynamo-archive"
>	gyp ERR! cwd /Users/my_user/node_modules/dynamo-archive/node_modules/sleep
>	gyp ERR! node -v v0.12.7
>	gyp ERR! node-gyp -v v2.0.1
>	gyp ERR! not ok
>	[sleep]: Error: Failed to execute 'node-gyp rebuild dynamo-archive' (1)
>	sh: nodejs: command not found
>	npm ERR! Darwin 14.4.0
>	npm ERR! argv "node" "/usr/local/bin/npm" "install" "dynamo-archive"
>	npm ERR! node v0.12.7
>	npm ERR! npm  v2.12.1
>	npm ERR! file sh
>	npm ERR! code ELIFECYCLE
>	npm ERR! errno ENOENT
>	npm ERR! syscall spawn
>
>	npm ERR! sleep@1.1.8 install: `node build.js || nodejs build.js`
>	npm ERR! spawn ENOENT
>	npm ERR!
>	npm ERR! Failed at the sleep@1.1.8 install script 'node build.js || nodejs build.js'.
>	npm ERR! This is most likely a problem with the sleep package,
>	npm ERR! not with npm itself.
>	npm ERR! Tell the author that this fails on your system:
>	npm ERR!     node build.js || nodejs build.js
>	npm ERR! You can get their info via:
>	npm ERR!     npm owner ls sleep
>	npm ERR! There is likely additional logging output above.
>
>	npm ERR! Please include the following file with any support request:
>	npm ERR!     /Users/my_user/npm-debug.log

**Comment by yegor256** [comment]
@jimmys here is the problem: 

```
sh: nodejs: command not found
```

Make sure `nodejs` and `node

**Comment by jimmys** [comment]
Thank you for that tip. I symlinked nodejs to the node binary on my machine and verified they are both executable (note, I am uncertain what the difference between them should be, and searching Google this morning did not turn up a conclusive answer).

> $ ll /usr/local/bin | grep node
> lrwxr-xr-x  1 my_user         admin        30 Jul 26 00:21 node -> ../Cellar/node/0.12.7/bin/node
> lrwxr-xr-x  1 my_user         admin        29 Jul 26 11:54 nodejs -> ../Cellar/node/0.12.7/bin/node
> lrwxr-xr-x  1 my_user         admin        46 Jul 26 00:22 npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
> 
> $ node -v
> v0.12.7
> 
> $ nodejs -v
> v0.12.7

It looks like the problem is now that sleep 1.1.8 won't build and install. Is there a way for me to update the dynamo-archive application to build against a newer version of sleep, which does build and install correctly for me?

>
> $ npm install sleep
> -
> > sleep@2.0.0 install /Users/my_user/node_modules/sleep
> > node-gyp rebuild
> 
>   CXX(target) Release/obj.target/node_sleep/sleep.o
>   SOLINK_MODULE(target) Release/node_sleep.node
> sleep@2.0.0 node_modules/sleep
> └── nan@1.8.4

> $ npm install sleep@1.1.8
> /
> > sleep@1.1.8 install /Users/my_user/node_modules/sleep
> > node build.js || nodejs build.js
> 
> child_process: customFds option is deprecated, use stdio instead.
> gyp: sleep@1.1.8 not found (cwd: /Users/my_user/node_modules/sleep) while trying to load sleep@1.1.8
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
> gyp ERR! System Darwin 14.4.0
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "sleep@1.1.8"
> gyp ERR! cwd /Users/my_user/node_modules/sleep
> gyp ERR! node -v v0.12.7
> gyp ERR! node-gyp -v v2.0.1
> gyp ERR! not ok
> [sleep]: Error: Failed to execute 'node-gyp rebuild sleep@1.1.8' (1)
> child_process: customFds option is deprecated, use stdio instead.
> gyp: sleep@1.1.8 not found (cwd: /Users/my_user/node_modules/sleep) while trying to load sleep@1.1.8
> gyp ERR! configure error
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
> gyp ERR! System Darwin 14.4.0
> gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "sleep@1.1.8"
> gyp ERR! cwd /Users/my_user/node_modules/sleep
> gyp ERR! node -v v0.12.7
> gyp ERR! node-gyp -v v2.0.1
> gyp ERR! not ok
> [sleep]: Error: Failed to execute 'node-gyp rebuild sleep@1.1.8' (1)
> npm ERR! Darwin 14.4.0
> npm ERR! argv "node" "/usr/local/bin/npm" "install" "sleep@1.1.8"
> npm ERR! node v0.12.7
> npm ERR! npm  v2.12.1
> npm ERR! code ELIFECYCLE
> 
> npm ERR! sleep@1.1.8 install: `node build.js || nodejs build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the sleep@1.1.8 install script 'node build.js || nodejs build.js'.
> npm ERR! This is most likely a problem with the sleep package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node build.js || nodejs build.js
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls sleep
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/my_user/npm-debug.log

**Comment by yegor256** [comment]
@jimmys why are you installing sleep 1.1.8? our `packages.json` says `1.1.x`. How can I reproduce the problem you're having? You're supposed to run:

```
npm install dynamo-archive
```

**Comment by jimmys** [comment]
I am running the command you suggest. When I run npm install dynamo-archive it tries to install sleep 1.1.8, and fails. Thus dynamo-archive does not install.

I am able to reproduce this on my mac by having a clean Node install at the versions I quoted above and then running npm install dynamo-archive.

I posted that log above to show that sleep 1.1.8 does not install, but sleep 2.0 does. I wonder, do you just need to update the package to use a newer version of sleep and it will fix my problem?

**Comment by yegor256** [comment]
@jimmys this is what I have on my Mac:

```
$ npm install dynamo-archive
/
> sleep@1.1.8 install /Volumes/ssd2/code/blog/node_modules/dynamo-archive/node_modules/sleep
> node build.js || nodejs build.js

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
  CXX(target) Release/obj.target/node_sleep/sleep.o
  SOLINK_MODULE(target) Release/node_sleep.node
  SOLINK_MODULE(target) Release/node_sleep.node: Finished
[sleep]: Created: Build/Release
[sleep]: Installed in Build/Release/node_sleep.node
dynamo-archive@0.1.0 node_modules/dynamo-archive
├── dotenv@0.4.0
├── minimist@1.1.2
├── aws-sdk@2.0.31 (xmlbuilder@0.4.2, xml2js@0.2.6)
└── sleep@1.1.8 (mkdirp@0.3.5)
```

**Comment by yegor256** [comment]
@jimmys there is something wrong with your local `npm`, I suspect :(

**Comment by andy-c-jones** [comment]
Just ran into this issue and also tested with a fresh OS image with a fresh npm install. Still happens.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@jimmys @andy-c-jones as you see in http://www.rultor.com/t/5524-149631058 - it installs well on Ubuntu 14.04

**Comment by jimmys** [comment]
I moved on from this software due to the installation issues, so I won't be able to help any more.

**Comment by andy-c-jones** [comment]
@yegor256 I was using the amazon linux ami if that helps you investigate.

**Comment by yegor256** [comment]
@andy-c-jones do you remember which AMI specifically?
