### ISSUE TITLE
dynamo-restore bombs out during restore attempt

### ISSUE THREAD

**Issue by mbravorus** [yegor256/dynamo-archive#24]
when attempting to restore a previously backed up table, restore operation throws an exception, not immediately obvious what is wrong here:

```
$ ./dynamo-restore.js --table development.main.clans_b < ~/fs.main.clans-150316 
{"data":{"B":{"type":"Buffer","data":[120,156,171,86,202,205,47,73,81,178,82,82,170,5,0,22,50,3,111]}},"clan_id":{"N":"251"}}
{ [InvalidParameterType: Expected params.Item['data'].B to be a string, Buffer, Stream, Blob, or typed array object]
  message: 'Expected params.Item[\'data\'].B to be a string, Buffer, Stream, Blob, or typed array object',
  code: 'InvalidParameterType',
  time: Tue Mar 15 2016 13:55:12 GMT+0000 (UTC) } 'InvalidParameterType: Expected params.Item[\'data\'].B to be a string, Buffer, Stream, Blob, or typed array object\n    at ParamValidator.fail (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:50:37)\n    at ParamValidator.validatePayload (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:251:10)\n    at ParamValidator.validateScalar (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:133:21)\n    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:94:21)\n    at ParamValidator.validateStructure (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:75:14)\n    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:88:21)\n    at ParamValidator.validateMap (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:117:14)\n    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:92:21)\n    at ParamValidator.validateStructure (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:75:14)\n    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:88:21)'
readline.js:925
            throw err;
            ^

InvalidParameterType: Expected params.Item['data'].B to be a string, Buffer, Stream, Blob, or typed array object
    at ParamValidator.fail (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validatePayload (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:251:10)
    at ParamValidator.validateScalar (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:133:21)
    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:94:21)
    at ParamValidator.validateStructure (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validateMap (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:117:14)
    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:92:21)
    at ParamValidator.validateStructure (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:75:14)
    at ParamValidator.validateMember (/opt/dynamo-archive/node_modules/aws-sdk/lib/param_validator.js:88:21)
```

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@mbravorus hm.. interesting. did you create this `~/fs.main.clans-150316` with the same version of this library?

**Comment by mbravorus** [comment]
@yegor256 yep, same version

**Comment by yegor256** [comment]
@miccolis would you be interested to reproduce this situation in a test and fix?
